spring.application.name=TimeOrganiser
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url = jdbc:postgresql://ep-divine-voice-ale0rzn2-pooler.c-3.eu-central-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_aqt8uF1ApZwj&sslmode=require&channelBinding=require
spring.datasource.username= neondb_owner
spring.datasource.password = npg_aqt8uF1ApZwj
spring.datasource.hikari.initialization-fail-timeout=30000
spring.datasource.hikari.connection-timeout=30000

spring.datasource.hikari.keepalive-time=30000
spring.datasource.hikari.max-lifetime=1800000
timeorganiser.app.jwtSecret=hgyrdr28yuiopk50mnbvcdrtyjnbvftyoiuytredcftyuioplkm67098642jdwsc
timeorganiser.app.jwtExpirationMs = 54000
